apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cardanoforgeclusters.cardano.io
  labels:
    app: cardano-forge-manager
    component: cluster-management
    version: v2.0.0
spec:
  group: cardano.io
  versions:
  - name: v1
    served: true
    storage: true
    additionalPrinterColumns:
    - name: Network
      type: string
      jsonPath: .spec.network.name
    - name: Pool
      type: string
      jsonPath: .spec.pool.ticker
    - name: State
      type: string
      jsonPath: .status.effectiveState
    - name: Priority
      type: integer
      jsonPath: .status.effectivePriority
    - name: Active Leader
      type: string
      jsonPath: .status.activeLeader
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required:
            - network
            - pool
            - region
            properties:
              # Network Configuration (Required)
              network:
                type: object
                required:
                - name
                - magic
                properties:
                  name:
                    type: string
                    enum: ["mainnet", "preprod", "preview", "custom"]
                    description: "Cardano network name"
                  magic:
                    type: integer
                    description: "Network magic number for the target network"
                  era:
                    type: string
                    description: "Current era name (e.g., 'conway', 'babbage')"
                    default: "conway"
                
              # Pool Configuration (Required)
              pool:
                type: object
                required:
                - id
                - idHex
                properties:
                  id:
                    type: string
                    pattern: '^pool1[a-z0-9]{51}$'
                    description: "Pool ID in bech32 format"
                  idHex:
                    type: string
                    pattern: '^[a-f0-9]{56}$'
                    description: "Pool ID in hex format"
                  name:
                    type: string
                    description: "Human-readable pool name"
                    maxLength: 50
                  ticker:
                    type: string
                    description: "Pool ticker symbol"
                    pattern: '^[A-Z0-9]{1,5}$'
                  description:
                    type: string
                    description: "Pool description"
                    maxLength: 255
                  
              # Application Configuration (Optional)
              application:
                type: object
                properties:
                  type:
                    type: string
                    enum: ["block-producer", "relay-only", "monitoring", "custom"]
                    default: "block-producer"
                    description: "Application type classification"
                  version:
                    type: string
                    description: "Application/cardano-node version"
                  environment:
                    type: string
                    enum: ["production", "staging", "development", "testing"]
                    default: "production"
                    description: "Environment classification"
                    
              # Regional Configuration (Required)
              region:
                type: string
                description: "Geographic region identifier"
                pattern: '^[a-z0-9\-]{2,20}$'
              
              # Forge State Configuration
              forgeState:
                type: string
                enum: ["Enabled", "Disabled", "Priority-based"]
                default: "Priority-based"
                description: "Desired forge state for this pool"
                
              # Priority Configuration
              priority:
                type: integer
                minimum: 1
                maximum: 999
                default: 100
                description: "Base priority for this pool (lower = higher priority)"
                
              # Health Check Configuration
              healthCheck:
                type: object
                properties:
                  enabled:
                    type: boolean
                    default: false
                    description: "Enable health check monitoring"
                  endpoint:
                    type: string
                    format: uri
                    description: "HTTP endpoint for health checks"
                  interval:
                    type: string
                    pattern: '^[0-9]+[smh]$'
                    default: "30s"
                    description: "Health check interval"
                  timeout:
                    type: string
                    pattern: '^[0-9]+[smh]$'
                    default: "10s"
                    description: "Health check timeout"
                  failureThreshold:
                    type: integer
                    minimum: 1
                    maximum: 10
                    default: 3
                    description: "Number of consecutive failures before marking unhealthy"
                  headers:
                    type: object
                    additionalProperties:
                      type: string
                    description: "Additional HTTP headers for health checks"
                    
              # Override Configuration (Manual Failover)
              override:
                type: object
                properties:
                  enabled:
                    type: boolean
                    default: false
                    description: "Enable manual override"
                  reason:
                    type: string
                    description: "Reason for manual override"
                  expiresAt:
                    type: string
                    format: date-time
                    description: "Override expiration time (ISO 8601)"
                  forcePriority:
                    type: integer
                    minimum: 1
                    maximum: 999
                    description: "Override priority value"
                  forceState:
                    type: string
                    enum: ["Enabled", "Disabled"]
                    description: "Override forge state"
                    
          status:
            type: object
            properties:
              # Effective State (Computed)
              effectiveState:
                type: string
                enum: ["Enabled", "Disabled", "Priority-based"]
                description: "Current effective forge state"
              effectivePriority:
                type: integer
                description: "Current effective priority (may include health adjustments)"
              
              # Network Status
              networkStatus:
                type: object
                properties:
                  network:
                    type: string
                    description: "Current network"
                  magic:
                    type: integer
                    description: "Current network magic"
                  syncStatus:
                    type: string
                    enum: ["syncing", "synced", "behind", "unknown"]
                    description: "Node sync status"
                  tipSlot:
                    type: integer
                    description: "Current tip slot number"
                  tipHash:
                    type: string
                    description: "Current tip block hash"
                  epochNo:
                    type: integer
                    description: "Current epoch number"
                    
              # Pool Status
              poolStatus:
                type: object
                properties:
                  poolId:
                    type: string
                    description: "Pool ID"
                  activeStake:
                    type: string
                    description: "Active stake amount (lovelace)"
                  delegatorCount:
                    type: integer
                    description: "Number of delegators"
                  lastBlockProduced:
                    type: string
                    format: date-time
                    description: "Timestamp of last block produced"
                  blocksProducedEpoch:
                    type: integer
                    description: "Blocks produced in current epoch"
                  blocksExpectedEpoch:
                    type: integer
                    description: "Blocks expected in current epoch"
                    
              # Leadership Status
              activeLeader:
                type: string
                description: "Pod name of current active leader (if any)"
              forgingEnabled:
                type: boolean
                description: "Whether forging is currently enabled"
              lastTransition:
                type: string
                format: date-time
                description: "Last state transition timestamp"
                
              # Health Status
              healthStatus:
                type: object
                properties:
                  healthy:
                    type: boolean
                    description: "Current health status"
                  lastProbeTime:
                    type: string
                    format: date-time
                    description: "Last health check timestamp"
                  consecutiveFailures:
                    type: integer
                    description: "Number of consecutive health check failures"
                  message:
                    type: string
                    description: "Health status message"
                  responseTime:
                    type: string
                    description: "Last health check response time"
                    
              # Conditions
              conditions:
                type: array
                items:
                  type: object
                  required:
                  - type
                  - status
                  - lastTransitionTime
                  properties:
                    type:
                      type: string
                      enum: ["Ready", "HealthCheckPassing", "LeaderElected", "Syncing"]
                    status:
                      type: string
                      enum: ["True", "False", "Unknown"]
                    lastTransitionTime:
                      type: string
                      format: date-time
                    reason:
                      type: string
                    message:
                      type: string
    subresources:
      status: {}
  scope: Namespaced
  names:
    plural: cardanoforgeclusters
    singular: cardanoforgeluster
    kind: CardanoForgeCluster
    shortNames:
    - cfc
    categories:
    - cardano
    - blockchain

---
# RBAC for multi-tenant CardanoForgeCluster management
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cardano-forge-manager-multi-tenant
  labels:
    app: cardano-forge-manager
    component: rbac
rules:
# CardanoForgeCluster CRD permissions
- apiGroups: ["cardano.io"]
  resources: ["cardanoforgeclusters"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: ["cardano.io"]
  resources: ["cardanoforgeclusters/status"]
  verbs: ["get", "update", "patch"]
  
# Lease coordination (scoped per pool)
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  resourceNames: [] # Will be restricted by pool-specific lease names
  
# Pod and node information (read-only)
- apiGroups: [""]
  resources: ["pods", "nodes"]
  verbs: ["get", "list", "watch"]
  
# Events for debugging
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cardano-forge-manager-multi-tenant
  labels:
    app: cardano-forge-manager
    component: rbac
subjects:
- kind: ServiceAccount
  name: cardano-forge-manager
  namespace: default # This will be overridden per deployment
roleRef:
  kind: ClusterRole
  name: cardano-forge-manager-multi-tenant
  apiGroup: rbac.authorization.k8s.io