# Test configuration demonstrating Prometheus backend setup
# Use: helm template test ./charts/cardano-node --values ./examples/prometheus-config-test.yaml

# Basic node configuration
cardanoNode:
  network: "preprod"
  blockProducer: false  # Relay node for testing
  
  # Prometheus configuration
  prometheus:
    enabled: true  # This enables PrometheusSimple backend
    host: "0.0.0.0"
    port: 12798
  
  # Mithril disabled for testing
  mithril:
    enabled: false

# Health checks - readiness probe will be enabled since Prometheus is enabled
healthChecks:
  cardanoNode:
    livenessProbe:
      enabled: false  # Disabled to prevent restarts
    readinessProbe:
      enabled: true   # Will only be active when prometheus.enabled=true

# Forge manager disabled for this relay test
forgeManager:
  enabled: false

# Test with minimal resources
resources:
  cardanoNode:
    requests:
      cpu: 100m
      memory: 1Gi
    limits:
      cpu: 500m
      memory: 2Gi

# Use smaller storage for testing
persistence:
  enabled: true
  size: 50Gi