{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "cardano-node.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cardano-node.labels" . | nindent 4 }}
  {{- with .Values.networkPolicy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      {{- include "cardano-node.selectorLabels" . | nindent 6 }}
  policyTypes:
    {{- if .Values.networkPolicy.ingress }}
    - Ingress
    {{- end }}
    {{- if .Values.networkPolicy.egress }}
    - Egress
    {{- end }}
  {{- if .Values.networkPolicy.ingress }}
  ingress:
    # Allow P2P traffic from anywhere (block producers and relays need to be publicly accessible)
    - ports:
        - protocol: TCP
          port: {{ .Values.service.p2p.port }}
      {{- if .Values.networkPolicy.ingress.p2pFromCIDR }}
      from:
        - ipBlock:
            cidr: {{ .Values.networkPolicy.ingress.p2pFromCIDR }}
      {{- end }}
    
    # Allow Prometheus metrics scraping from monitoring namespace
    {{- if .Values.monitoring.enabled }}
    - ports:
        - protocol: TCP
          port: {{ .Values.cardanoNode.prometheusPort }}
      from:
        {{- if .Values.networkPolicy.ingress.metricsFromNamespaces }}
        {{- range .Values.networkPolicy.ingress.metricsFromNamespaces }}
        - namespaceSelector:
            matchLabels:
              name: {{ . }}
        {{- end }}
        {{- else }}
        # Default: allow from same namespace
        - podSelector: {}
        {{- end }}
    {{- end }}
    
    # Allow Forge Manager metrics scraping
    {{- if .Values.forgeManager.enabled }}
    - ports:
        - protocol: TCP
          port: {{ .Values.forgeManager.metricsPort }}
      from:
        {{- if .Values.networkPolicy.ingress.metricsFromNamespaces }}
        {{- range .Values.networkPolicy.ingress.metricsFromNamespaces }}
        - namespaceSelector:
            matchLabels:
              name: {{ . }}
        {{- end }}
        {{- else }}
        # Default: allow from same namespace
        - podSelector: {}
        {{- end }}
    {{- end }}
    
    # Allow Submit API traffic (if enabled)
    {{- if .Values.submitApi.enabled }}
    - ports:
        - protocol: TCP
          port: {{ .Values.submitApi.port }}
      {{- if .Values.networkPolicy.ingress.submitApiFrom }}
      from:
        {{- toYaml .Values.networkPolicy.ingress.submitApiFrom | nindent 8 }}
      {{- end }}
    {{- end }}
    
    # Allow inter-pod communication (for leader election, health checks, etc.)
    - from:
        - podSelector:
            matchLabels:
              {{- include "cardano-node.selectorLabels" . | nindent 14 }}
    
    # Custom ingress rules
    {{- with .Values.networkPolicy.ingress.customRules }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  
  {{- if .Values.networkPolicy.egress }}
  egress:
    # Allow DNS resolution
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    
    # Allow outbound P2P to Cardano network
    - ports:
        - protocol: TCP
          port: {{ .Values.service.p2p.port }}
      {{- if .Values.networkPolicy.egress.p2pToCIDR }}
      to:
        - ipBlock:
            cidr: {{ .Values.networkPolicy.egress.p2pToCIDR }}
      {{- end }}
    
    # Allow HTTPS for downloading genesis files, Mithril snapshots, etc.
    - ports:
        - protocol: TCP
          port: 443
      {{- if .Values.networkPolicy.egress.httpsToCIDR }}
      to:
        - ipBlock:
            cidr: {{ .Values.networkPolicy.egress.httpsToCIDR }}
      {{- end }}
    
    # Allow Kubernetes API server access (for Forge Manager)
    {{- if .Values.forgeManager.enabled }}
    - ports:
        - protocol: TCP
          port: 443
      to:
        - namespaceSelector:
            matchLabels:
              name: default
          podSelector:
            matchLabels:
              component: apiserver
    {{- end }}
    
    # Allow health check endpoint (if configured)
    {{- if and .Values.forgeManager.enabled .Values.forgeManager.clusterManagement.enabled .Values.forgeManager.clusterManagement.healthCheck.enabled }}
    - ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
      {{- if .Values.networkPolicy.egress.healthCheckTo }}
      to:
        {{- toYaml .Values.networkPolicy.egress.healthCheckTo | nindent 8 }}
      {{- end }}
    {{- end }}
    
    # Allow inter-pod communication
    - to:
        - podSelector:
            matchLabels:
              {{- include "cardano-node.selectorLabels" . | nindent 14 }}
    
    # Custom egress rules
    {{- with .Values.networkPolicy.egress.customRules }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
